global:
  resolve_timeout: 10s   # время ожидания, после которого повторно отправлять уведомление

route:
  receiver: "default-receiver"
  routes:
    - receiver: "postgres-receiver"
      matchers:
        - job="postgres"

receivers:
  - name: "default-receiver"
  - name: "postgres-receiver"
    telegram_configs:
      - bot_token: "BOT_TOKEN"
        chat_id: CHAT_ID (с минусом, без ковычек)
        api_url: "https://api.telegram.org"
        parse_mode: "HTML"
        send_resolved: true
