global:
  # Scrape-интервал для таргетов
  scrape_interval: 5s
  # Интервал, с которым будут запускаться все rule-группы по умолчанию
  evaluation_interval: 10s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
